#!/bin/bash

. ./tools.sh

# Set sudo
if [ "$PM" = "apt" ]
then
    SUDO="sudo"
else
    SUDO=""
fi

WORKPATH=$PWD

if [ ! -d $WORKPATH/services ]
then
    mkdir $WORKPATH/services
fi

help_info()
{
    echo -e "Name:"
    echo -e "        DockerSH"
    echo -e "Program:"
    echo -e "        DockerSH is a shell about docker manage"
    echo -e "Version:"
    echo -e "        1.0.3"
    echo -e "History:"
    echo -e "        Created on 2018/07/16"
    echo -e "        Last modified on 2021/01/10"
    echo -e "Author:"
    echo -e "        kwkw"
    echo -e "Commands:"
    echo -e "        up              Up the container"
    echo -e "        reup            docker stop container && docker rm container && up"
    echo -e "        ps              docker ps"
    echo -e "        psall           docker ps -a"
    echo -e "        start           docker start container"
    echo -e "        startall        docker start \`docker ps -a -q\`"
    echo -e "        stop            docker stop container"
    echo -e "        stopall         docker stop \`docker ps -a -q\`"
    echo -e "        restart         docker stop container && docker start container"
    echo -e "        restartall      docker stop \`docker ps -a -q\` && docker start \`docker ps -a -q\`"
    echo -e "        logs            docker logs -f container"
    echo -e "        rm              docker rm container"
    echo -e "        rmall           docker rm \`docker ps -a -q\`"
    echo -e "        down            docker stop container && docker rm container"
    echo -e "        downall         docker stop \`docker ps -a -q\` && docker rm \`docker ps -a -q\`"
    echo -e "        images          docker images"
    echo -e "        rmi             docker rmi image"
    echo -e "        rmiall          docker rmi \`docker images -q\`"
    echo -e "        help | -h       Help info"
    echo -e "Options:"
    echo -e "        x, --xxx \tName of container (command: up)"
}

up_one()
{
    cd $WORKPATH/services
    DOCKER_COMPOSE_YML_PATH=$WORKPATH/docker-compose.yml

    if [ -f ./$option/docker-compose.yml ]
    then
        cat ./$option/docker-compose.yml > $DOCKER_COMPOSE_YML_PATH
        echo -e "$option will be up"
        cd $WORKPATH
        $SUDO docker-compose up -d
        exit 0
    fi

    echo -e "$option $option/docker-compose.yml file does not exist"
    exit 1
}

up_common_start()
{
    case "$option" in
      "" )
          echo -e "Please enter a container name\n"
          exit 1
          ;;
      * )
          up_one
          exit 0
          ;;
    esac
}

y_or_n()
{
    read -p "Are you sure [y/N]:" y_n
    echo "$y_n"
    if [ "$y_n" = "y" ] || [ "$y_n" = "Y" ]
    then
        :
    else
        echo -e "Cancel"
        exit 0
    fi
}

y_or_n_three_times()
{
    y_or_n
    y_or_n
    y_or_n
}

if [ $# -gt 2 ]
then
    echo -e "Too many parameters. See 'dockerSH -h'\n"
    exit 1
elif [ $# -lt 1 ]
then
    help_info
    exit 0
fi

option="$2"
case "$1" in
  "up" )
      up_common_start
      ;;
  "reup" )
      y_or_n_three_times
      $SUDO docker stop "$option" && $SUDO docker rm "$option" && up_common_start
      ;;
  "ps" )
      $SUDO docker ps
      ;;
  "psall" )
      $SUDO docker ps -a
      ;;
  "start" )
      $SUDO docker start "$option"
      ;;
  "startall" )
      $SUDO docker start `$SUDO docker ps -a -q`
      ;;
  "stop" )
      $SUDO docker stop "$option"
      ;;
  "stopall" )
      $SUDO docker stop `$SUDO docker ps -a -q`
      ;;
  "restart" )
      $SUDO docker stop "$option" && docker start "$option"
      ;;
  "restartall" )
      $SUDO docker stop `$SUDO docker ps -a -q` && $SUDO docker start `$SUDO docker ps -a -q`
      ;;
  "logs" )
      $SUDO docker logs -f "$option"
      ;;
  "rm" )
      y_or_n_three_times
      $SUDO docker rm "$option"
      ;;
  "rmall" )
      y_or_n_three_times
      $SUDO docker rm `$SUDO docker ps -a -q`
      ;;
  "down" )
      y_or_n_three_times
      $SUDO docker stop "$option" && $SUDO docker rm "$option"
      ;;
  "downall" )
      y_or_n_three_times
      $SUDO docker stop `$SUDO docker ps -a -q` && $SUDO docker rm `$SUDO docker ps -a -q`
      ;;
  "images" )
      $SUDO docker images
      ;;
  "rmi" )
      y_or_n_three_times
      $SUDO docker rmi "$option"
      ;;
  "rmiall" )
      y_or_n_three_times
      $SUDO docker rmi `$SUDO docker images -q`
      ;;
  "help" | "-h" )
      help_info
      ;;
  * )
      echo -e "Error command. See 'dockerSH -h'\n"
      exit 1
      ;;
esac
