version: '2'
services:
  mariadb-example:
    restart: always
    image: mariadb:10.5.8
    container_name: mariadb-example
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    expose:
      - "3306"
    volumes:
      - ../data/mariadb-example:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mariadb-example
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=12345678
